tasks:
  - init: npm install
    command: npm run start

ports:
  - port: 3000
    onOpen: "open-preview"
    visibility: private

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - prisma.vscode-graphql
    - esbenp.prettier-vscode
